# -*- coding: utf-8 -*-
"""task1_data_collection.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O350Z9KscITwcHg_ZMo84wIuXvhnx_zg
"""

import requests
import json
import os
import time
from datetime import datetime

TOP_STORIES_URL = "https://hacker-news.firebaseio.com/v0/topstories.json"
ITEM_URL = "https://hacker-news.firebaseio.com/v0/item/{}.json"

headers = {"User-Agent": "TrendPulse/1.0"}

categories = {
    "technology": ["ai", "software", "tech", "code", "computer", "data", "cloud", "api", "gpu", "llm"],
    "worldnews": ["war", "government", "country", "president", "election", "climate", "attack", "global"],
    "sports": ["nfl", "nba", "fifa", "sport", "team", "player", "league", "championship"],
    "science": ["research", "study", "space", "physics", "biology", "discovery", "nasa", "genome"],
    "entertainment": ["movie", "film", "music", "netflix", "book", "show", "award", "streaming"]
}

def get_category(title):
    title = title.lower()
    for category, keywords in categories.items():
        for word in keywords:
            if word in title:
                return category
    return "technology"  # fallback

try:
    response = requests.get(TOP_STORIES_URL, headers=headers)
    story_ids = response.json()[:1000]
except Exception as e:
    print("Error fetching top stories:", e)
    exit()

collected_data = []

for story_id in story_ids:
    try:
        res = requests.get(ITEM_URL.format(story_id), headers=headers)
        story = res.json()

        if not story or "title" not in story:
            continue

        category = get_category(story["title"])

        data = {
            "post_id": story.get("id"),
            "title": story.get("title"),
            "category": category,
            "score": story.get("score", 0),
            "num_comments": story.get("descendants", 0),
            "author": story.get("by"),
            "collected_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        }

        collected_data.append(data)

        # stop at 125 total
        if len(collected_data) >= 125:
            break

    except Exception as e:
        print(f"Error fetching story {story_id}: {e}")
        continue

# Sleep once per category (requirement)
for _ in categories:
    time.sleep(2)

# Save JSON
os.makedirs("data", exist_ok=True)
filename = f"data/trends_{datetime.now().strftime('%Y%m%d')}.json"

with open(filename, "w") as f:
    json.dump(collected_data, f, indent=4)

print(f"Collected {len(collected_data)} stories. Saved to {filename}")