# -*- coding: utf-8 -*-
"""task3_analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O350Z9KscITwcHg_ZMo84wIuXvhnx_zg
"""

import pandas as pd
import numpy as np
import os

# -------------------------------
# 1. LOAD AND EXPLORE DATA
# -------------------------------

file_path = "data/trends_clean.csv"

try:
    df = pd.read_csv(file_path)
    print(f"Loaded data: {df.shape}")
except Exception as e:
    print("Error loading CSV:", e)
    exit()

# First 5 rows
print("\nFirst 5 rows:")
print(df.head())

# Average values
avg_score = df["score"].mean()
avg_comments = df["num_comments"].mean()

print(f"\nAverage score   : {avg_score:.2f}")
print(f"Average comments: {avg_comments:.2f}")

# -------------------------------
# 2. NUMPY ANALYSIS
# -------------------------------

scores = df["score"].values
comments = df["num_comments"].values

print("\n--- NumPy Stats ---")

print(f"Mean score   : {np.mean(scores):.2f}")
print(f"Median score : {np.median(scores):.2f}")
print(f"Std deviation: {np.std(scores):.2f}")

print(f"Max score    : {np.max(scores)}")
print(f"Min score    : {np.min(scores)}")

# Category with most stories
category_counts = df["category"].value_counts()
top_category = category_counts.idxmax()
top_count = category_counts.max()

print(f"\nMost stories in: {top_category} ({top_count} stories)")

# Story with most comments
max_comments_index = np.argmax(comments)
top_story_title = df.iloc[max_comments_index]["title"]
top_story_comments = comments[max_comments_index]

print(f"\nMost commented story: \"{top_story_title}\" — {top_story_comments} comments")

# -------------------------------
# 3. ADD NEW COLUMNS
# -------------------------------

# Engagement = comments per score
df["engagement"] = df["num_comments"] / (df["score"] + 1)

# is_popular column
df["is_popular"] = df["score"] > avg_score

# -------------------------------
# 4. SAVE RESULT
# -------------------------------

os.makedirs("data", exist_ok=True)

output_file = "data/trends_analysed.csv"
df.to_csv(output_file, index=False)

print(f"\nSaved to {output_file}")