# -*- coding: utf-8 -*-
"""task2_data_processing

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O350Z9KscITwcHg_ZMo84wIuXvhnx_zg
"""

import pandas as pd
import os

# File path (make sure name matches your JSON file)
file_path = "data/trends_20260414.json"

# -------------------------------
# 1. LOAD JSON FILE
# -------------------------------
try:
    df = pd.read_json(file_path)
    print(f"Loaded {len(df)} stories from {file_path}")
except Exception as e:
    print("Error loading JSON:", e)
    exit()

# -------------------------------
# 2. CLEAN THE DATA
# -------------------------------

# Remove duplicates based on post_id
before = len(df)
df = df.drop_duplicates(subset="post_id")
print(f"After removing duplicates: {len(df)}")

# Remove rows with missing values in important columns
df = df.dropna(subset=["post_id", "title", "score"])
print(f"After removing nulls: {len(df)}")

# Convert data types
df["score"] = df["score"].astype(int)
df["num_comments"] = df["num_comments"].astype(int)

# Remove low-quality stories (score < 5)
df = df[df["score"] >= 5]
print(f"After removing low scores: {len(df)}")

# Remove extra whitespace from title
df["title"] = df["title"].str.strip()

# -------------------------------
# 3. SAVE AS CSV
# -------------------------------
os.makedirs("data", exist_ok=True)

output_file = "data/trends_clean.csv"
df.to_csv(output_file, index=False)

print(f"\nSaved {len(df)} rows to {output_file}")

# -------------------------------
# CATEGORY SUMMARY
# -------------------------------
print("\nStories per category:")
print(df["category"].value_counts())